In [1]:
#import library
import numpy as np

In [6]:
#Create a NumPy array with 10 random integers between 0 and 100.
arr1=np.random.randint(0,100,size=10)
arr1

array([25,  5, 42, 44, 95, 88, 24, 12, 85, 33])

In [7]:
#Use the np.where() function to create a new array with the same shape as the previous one,
#where values less than 50 are replaced with -1 and values greater than or equal to 50 are
#replaced with 1.
answer=np.where(arr1<50,-1,1)
answer

array([-1, -1, -1, -1,  1,  1, -1, -1,  1, -1])

In [8]:
#Calculate the mean, median, and standard deviation of the original array.
np.mean(arr1)

45.3

In [9]:
np.median(arr1)

37.5

In [10]:
np.std(arr1)

31.03562469163461

In [12]:
#Create a boolean array that is True where the values in the original array are even, and False
#otherwise.
np.where(arr1%2==0,True,False)

array([False, False,  True,  True, False,  True,  True,  True, False,
       False])

In [14]:
#Sort the original array in ascending order
a=np.sort(arr1)
a

array([ 5, 12, 24, 25, 33, 42, 44, 85, 88, 95])

In [15]:
#6. Find the unique values in the original array.
np.unique(arr1)

array([ 5, 12, 24, 25, 33, 42, 44, 85, 88, 95])

In [16]:
#Use the np.in1d() function to create a boolean array indicating which elements of the original
#array are also present in a new array with 5 random integers between 0 and 100.
arr2=np.random.randint(0,100,size=5)
np.in1d(arr1,arr2)

array([False, False, False, False, False, False, False, False, False,
       False])

In [18]:
#Save the original array to a text file named "my_array.txt" using the np.savetxt() function.
np.savetxt("my_array.txt",arr1)