In [1]:
#import library
import numpy as np

In [4]:
#create a 1d NUMPY ARRAY WITH THE INTEGER FROM 0 TO 9
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#create 2d numpy array with shape (3,3) and fill it with zeros
np.zeros([3,3],'int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
#create 3D numpy array with shape (2,3,4) and fill it with ones
np.ones([2,3,4],'int')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [8]:
#create a numpy array with 10 random integer from 0 to 100
np.random.randint(100,size=(10))

array([98, 69, 96, 78, 75, 20,  4, 70, 49, 53])

In [9]:
#create a numpy array with 10 random flots between 0 and 1
np.random.rand(10)

array([0.86329614, 0.06291774, 0.90233988, 0.26356963, 0.54813783,
       0.97021001, 0.33330939, 0.19889243, 0.43448925, 0.79061022])

In [10]:
#create a numpy array with 5 equally spaced values between 0 and 1
np.linspace(0,1,num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
np.arange(0,1.1,.25)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
#create a numpy array with 5 equally spaced between 0 ad 10
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
##create a numpy array with 5 equally spaced between -1 and 1
np.linspace(-1,1,num=5)


array([-1. , -0.5,  0. ,  0.5,  1. ])

In [18]:
#create a numpy array with the sine values of angles between 0 and 2pi
np.sin(np.linspace(0, 2*np.pi,5))

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

In [19]:
#create a numpy array with the cosine values of angles between 0 and pi
np.cos(np.linspace(0, np.pi,5))

array([ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17, -7.07106781e-01,
       -1.00000000e+00])