In [1]:
#import library
import numpy as np

In [3]:
#create a 1D numpy array with the integers from 0 to 9.Extract the 3rd elements from the array
a=np.arange(0,10)
a[3]

3

In [10]:
#create a 2D numpy array with shape(3,3) and fill it with random numbers. Extract the elements 
#at row 2, column 1
b=np.array([[1,1,1],
           [2,2,2],
           [3,3,3]])
b[1][0]

2

In [9]:
#. Create a 2D NumPy array with shape (4, 4) and fill it with random numbers. Extract the subarray
#consisting of the first 2 rows and the last 2 columns
c=np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])
c[:2][]

array([[1, 1, 1, 1],
       [2, 2, 2, 2]])

In [11]:
d=np.random.randint(1,10,size=(4,4),dtype=int)

In [12]:
d

array([[6, 9, 1, 6],
       [7, 6, 5, 2],
       [3, 4, 1, 6],
       [4, 3, 7, 1]])

In [17]:
d[:2,-2:]

array([[1, 6],
       [5, 2]])

In [18]:
#Create a 1D NumPy array with the integers from 0 to 9. Copy a slice of the array consisting of the
#first 3 elements
f=np.arange(0,10)
f[:3]

array([0, 1, 2])

In [19]:
#Create a 2D NumPy array with shape (3, 3) and fill it with random numbers. Copy a slice of the
#array consisting of the first 2 rows and the first 2 columns.
l=np.random.randint(1,10,size=(3,3),dtype=int)
l

array([[5, 3, 7],
       [9, 8, 3],
       [5, 7, 7]])

In [20]:
l[:2,:2]

array([[5, 3],
       [9, 8]])

In [26]:
#Create a 1D NumPy array with the integers from 0 to 9. Reshape the array into a 2D array with
#shape (3, 3).
g=np.arange(0,9)
h=np.array(g)
h

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
h.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
#. Create a 2D NumPy array with shape (4, 4) and fill it with random numbers. Reshape the array
#into a 1D array.
d.flatten()

array([6, 9, 1, 6, 7, 6, 5, 2, 3, 4, 1, 6, 4, 3, 7, 1])

In [30]:
#Create two 1D NumPy arrays with the integers from 0 to 4. Concatenate the two arrays into a
#single 1D array.
a=np.arange(0,5)
b=np.arange(0,5)


In [34]:
c=np.concatenate((a,b))
c

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [44]:
#. Create two 2D NumPy arrays with shapes (2, 2) and (2, 3). Concatenate the two arrays
#horizontally.
a=np.random.randint(1,10,size=(2,2),dtype=int)
b=np.random.randint(1,10,size=(2,3),dtype=int)
c=np.hstack((a,b))
c

array([[4, 2, 8, 6, 4],
       [5, 7, 2, 5, 8]])

In [46]:
#10. Create two 2D NumPy arrays with shapes (2, 2) and (3, 2). Concatenate the two arrays vertically.
a=np.random.randint(1,10,size=(2,2),dtype=int)
b=np.random.randint(1,10,size=(3,2),dtype=int)
c=np.vstack((a,b))
c

array([[2, 7],
       [8, 1],
       [2, 8],
       [9, 4],
       [4, 8]])

In [53]:
arr=2+1.5*np.random.randn(5,5)
arr

array([[ 0.79744167,  2.05053591, -1.74179981,  0.86282975,  2.63038641],
       [ 3.95923553,  0.8828026 ,  2.63950793,  2.44816888,  0.90536845],
       [ 5.05062125,  0.55916783,  3.39733489,  4.42647012, -0.0649806 ],
       [-0.51877219,  2.25934255,  0.13383878,  1.28718184, -1.46961898],
       [ 1.11069223,  1.08989466,  3.51358896,  1.62614925,  2.32063661]])

In [ ]:
#Create a 2D NumPy array with shape (4, 4) and fill it with random numbers. Split the array into
#two equal horizontal halves.


In [54]:
#create array
A=np.array([-2,5,4,-8,0])
print(A)


[-2  5  4 -8  0]


In [55]:
print(np.sort(A)) #Ascending

[-8 -2  0  4  5]


In [57]:
print(np.flip(np.sort(A))) #Descending

[ 5  4  0 -2 -8]
