In [1]:
import numpy as np

In [2]:
l1=[1,2,3,4]

In [3]:
array1=np.array(l1)

In [4]:
array1

array([1, 2, 3, 4])

In [5]:
l2=[11,22,33,44]
l2

[11, 22, 33, 44]

In [6]:
l=[l1,l2]
l

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [7]:
array_2D=np.array(l)
array_2D

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [8]:
array_2D.shape

(2, 4)

In [9]:
array_2D.dtype

dtype('int32')

In [10]:
np.zeros(3,'int')

array([0, 0, 0])

In [11]:
np.ones(3,'int')

array([1, 1, 1])

In [12]:
np.ones([3,3],'int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
np.empty(4)

array([2.12199579e-314, 1.31351539e-311, 4.09086355e-321, 1.31352368e-311])

In [23]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [19]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])