In [1]:
#import library
import numpy as np

In [3]:
#create two 2*2 numpy arrays and calculates their product using the np.matmul() function
a1=np.array([[1,1],[2,2]])
a2=np.array([[1,1],[2,2]])
np.matmul(a1,a2)

array([[3, 3],
       [6, 6]])

In [4]:
#create two 3*3 numpy arrays and calculates their product using the np.dot() function
a1=np.array([[1,1,1],[2,2,2],[3,3,3]])
a2=np.array([[1,1,1],[2,2,2],[3,3,3]])
np.dot(a1,a2)

array([[ 6,  6,  6],
       [12, 12, 12],
       [18, 18, 18]])

In [6]:
#create two 2*3 numpy array and 3*2 numpy array and calculate their product using np.matmul()
a=np.array([[1,1,1],[2,2,2]])
b=np.array([[1,1],[2,2],[3,3]])
np.matmul(a,b)


array([[ 6,  6],
       [12, 12]])

In [7]:
np.dot(a,b)

array([[ 6,  6],
       [12, 12]])