In [2]:
#import library
import numpy as np

In [4]:
#create a 2*2 Numpy array and multiply it by 2
np.array([[1,1],[2,2]])*2

array([[2, 2],
       [4, 4]])

In [5]:
#create a 3*3 Numpy array add 5 to each elements
np.array([[1,1,1],[2,2,2],[3,3,3]])+5

array([[6, 6, 6],
       [7, 7, 7],
       [8, 8, 8]])

In [6]:
#create a 4*4 numpy array and subtract 10 from each elements
np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3],[4,4,4,4]])-10

array([[-9, -9, -9, -9],
       [-8, -8, -8, -8],
       [-7, -7, -7, -7],
       [-6, -6, -6, -6]])

In [9]:
#create a 5*5 numpy array and divide each element by 2
np.array([[2,2,2,2,2],
          [4,4,4,4,4],
         [6,6,6,6,6],
         [8,8,8,8,8],
         [10,10,10,10,10]])/2

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [13]:
#create a 6*6 numpy array and calculate the square root of each element
np.sqrt(np.array([[1, 1, 1, 1, 1,1],
       [2, 2, 2, 2, 2,2],
       [3, 3, 3, 3, 3,3],
       [4, 4, 4, 4, 4,4],
       [5, 5, 5, 5, 5,5],
       [6,6,6,6,6,6]]))

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        ],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356,
        1.41421356],
       [1.73205081, 1.73205081, 1.73205081, 1.73205081, 1.73205081,
        1.73205081],
       [2.        , 2.        , 2.        , 2.        , 2.        ,
        2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798,
        2.23606798],
       [2.44948974, 2.44948974, 2.44948974, 2.44948974, 2.44948974,
        2.44948974]])