In [1]:
#import library
import numpy as np

In [3]:
#. Create a NumPy array with shape (3,3) and fill it with random numbers. Use the np.exp()
#function to compute the exponential of each element in the array.
arr=np.random.randint(1,10,size=(3,3),dtype=int)
arr

array([[2, 2, 7],
       [5, 4, 1],
       [3, 3, 7]])

In [4]:
np.exp(arr)

array([[   7.3890561 ,    7.3890561 , 1096.63315843],
       [ 148.4131591 ,   54.59815003,    2.71828183],
       [  20.08553692,   20.08553692, 1096.63315843]])

In [6]:
#Create a NumPy array with shape (4,4) and fill it with random numbers. Use the np.sin() function
#to compute the sine of each element in the array.
arr2=np.random.randint(1,10,size=(4,4),dtype=int)
arr2

array([[6, 2, 7, 4],
       [3, 3, 1, 2],
       [9, 6, 2, 2],
       [5, 9, 9, 1]])

In [7]:
np.sin(arr2)

array([[-0.2794155 ,  0.90929743,  0.6569866 , -0.7568025 ],
       [ 0.14112001,  0.14112001,  0.84147098,  0.90929743],
       [ 0.41211849, -0.2794155 ,  0.90929743,  0.90929743],
       [-0.95892427,  0.41211849,  0.41211849,  0.84147098]])

In [8]:
#Create a NumPy array with shape (5,5) and fill it with random numbers. Use the np.log()
#function to compute the natural logarithm of each element in the array.
arr3=np.random.randint(1,10,size=(5,5),dtype=int)
arr3

array([[7, 4, 8, 5, 5],
       [7, 8, 9, 3, 9],
       [2, 2, 7, 7, 7],
       [2, 4, 2, 6, 9],
       [1, 7, 5, 2, 8]])

In [9]:
np.log(arr3)

array([[1.94591015, 1.38629436, 2.07944154, 1.60943791, 1.60943791],
       [1.94591015, 2.07944154, 2.19722458, 1.09861229, 2.19722458],
       [0.69314718, 0.69314718, 1.94591015, 1.94591015, 1.94591015],
       [0.69314718, 1.38629436, 0.69314718, 1.79175947, 2.19722458],
       [0.        , 1.94591015, 1.60943791, 0.69314718, 2.07944154]])

In [10]:
#Create a NumPy array with shape (2,2) and fill it with random numbers. Use the np.sqrt()
#function to compute the square root of each element in the array.
arr4=np.random.randint(1,10,size=(2,2),dtype=int)
arr4

array([[1, 7],
       [6, 5]])

In [11]:
np.sqrt(arr4)

array([[1.        , 2.64575131],
       [2.44948974, 2.23606798]])

In [12]:
#Create a NumPy array with shape (6,6) and fill it with random numbers. Use the np.floor()
#function to round down each element in the array to the nearest integer.
arr5=np.random.randint(1,10,size=(6,6),dtype=int)
arr5

array([[2, 4, 7, 3, 5, 3],
       [6, 2, 4, 2, 8, 5],
       [5, 1, 6, 7, 5, 1],
       [3, 2, 5, 7, 4, 5],
       [1, 4, 9, 1, 9, 2],
       [1, 9, 9, 3, 5, 4]])

In [13]:
np.floor(arr5)

array([[2., 4., 7., 3., 5., 3.],
       [6., 2., 4., 2., 8., 5.],
       [5., 1., 6., 7., 5., 1.],
       [3., 2., 5., 7., 4., 5.],
       [1., 4., 9., 1., 9., 2.],
       [1., 9., 9., 3., 5., 4.]])

In [14]:
#Create a NumPy array with shape (3,3) and fill it with random numbers. Use the np.abs()
#function to compute the absolute value of each element in the array.
arr6=np.random.randint(1,10,size=(3,3),dtype=int)
arr6

array([[5, 1, 4],
       [7, 9, 4],
       [1, 2, 6]])

In [15]:
np.abs(arr6)

array([[5, 1, 4],
       [7, 9, 4],
       [1, 2, 6]])

In [16]:
#Create a NumPy array with shape (4,4) and fill it with random numbers. Use the np.power()
#function to raise each element in the array to the power of 2.
arr7=np.random.randint(1,10,size=(4,4),dtype=int)
arr7

array([[4, 8, 6, 5],
       [8, 9, 4, 9],
       [7, 2, 3, 9],
       [9, 7, 7, 6]])

In [18]:
np.power(arr7,2)

array([[16, 64, 36, 25],
       [64, 81, 16, 81],
       [49,  4,  9, 81],
       [81, 49, 49, 36]], dtype=int32)

In [19]:
#Create a NumPy array with 5 random integers between 1 and 10. Use the maximum function to
#find the largest element in the array.
arr8=np.random.randint(1,10,size=5,dtype=int)
arr8

array([5, 7, 6, 5, 6])

In [20]:
np.max(arr8)

7

In [22]:
#Create a NumPy array with 10 random floating-point numbers between 0 and 1. Use the round
#function to round each element to the nearest integer.
arr9=np.random.rand(10)
arr9

array([0.59699158, 0.53971305, 0.9646726 , 0.10134814, 0.91379   ,
       0.59231266, 0.72490405, 0.19131941, 0.75518913, 0.57622789])

In [23]:
np.round(arr9)

array([1., 1., 1., 0., 1., 1., 1., 0., 1., 1.])

In [24]:
#Create a NumPy array with 7 random integers between 1 and 100. Use the argmax function to
#find the index of the largest element in the array.
arr10=np.random.randint(1,100,size=7,dtype=int)
arr10

array([65, 68, 70, 75, 28, 73, 69])

In [25]:
np.argmax(arr10)

3

In [26]:
#Create two NumPy arrays with the same shape, each filled with random integers between 1 and
#Use the add function to add the two arrays together element-wise.
arr11=np.random.randint(1,10,size=(4,4),dtype=int)
arr11

array([[5, 7, 8, 7],
       [9, 8, 7, 3],
       [6, 6, 5, 4],
       [4, 5, 1, 9]])

In [27]:
arr12=np.random.randint(1,10,size=(4,4),dtype=int)
arr12

array([[4, 1, 8, 1],
       [2, 3, 6, 2],
       [1, 9, 2, 8],
       [8, 2, 6, 3]])

In [29]:
np.add(arr11,arr12)

array([[ 9,  8, 16,  8],
       [11, 11, 13,  5],
       [ 7, 15,  7, 12],
       [12,  7,  7, 12]])

In [30]:
#Create a NumPy array with 12 random integers between 0 and 100. Use the clip function to limit
#the values in the array to a range between 10 and 90.
arr12=np.random.randint(0,100,size=12,dtype=int)
arr12

array([40, 65, 99, 18, 60, 17, 88, 62, 61, 81, 15,  3])

In [32]:
np.clip(arr12,10,90)

array([40, 65, 90, 18, 60, 17, 88, 62, 61, 81, 15, 10])